%YAML:1.0
cameras:
    - {T_SC:
       [0.009547907011793144, 0.9999388923125971, -0.00557217303674451, 0.04616411617875856,
        0.0023811991490284012, 0.00554967508977966, 0.9999817653322542, 0.04954854278330773,
        0.9999515825090272, -0.009561001362574428, -0.0023280658577522484, -0.4613320513182685,
          0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 480],
       distortion_coefficients: [-0.34001571326993424, 0.1192932397869883, 0.0002319090386160509, -0.0003695690527914604],
       distortion_type: radialtangential,
       focal_length: [438.40998075685343, 438.1044608734531], 
       principal_point: [326.23618753773263, 240.26141220544767]} 
    - {T_SC:
       [0.0024392916576993495, 0.9999813297834552, -0.005602672640921014, -0.04204602505663715,
        -0.002830206515046285, 0.005609570481532794, 0.999980261130236, 0.05176331631426951,
        0.9999930198692843, -0.0024233867882290094, 0.0028438370529567103, -0.4606527811186744,
          0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 480],
       distortion_coefficients: [-0.33927228663021836, 0.11840170078813175, 0.0006558802729960746, -4.651163926965988e-06],
       distortion_type: radialtangential,
       focal_length: [438.2222396545766, 438.06544669488954], 
       principal_point: [311.9268868846497, 248.189600928201]} 

camera_params:
    camera_rate: 30 # just to manage the expectations of when there should be frames arriving
    sigma_absolute_translation: 0.0 # The standard deviation of the camera extrinsics translation, e.g. 1.0e-10 for online-calib [m].
    sigma_absolute_orientation: 0.0 # The standard deviation of the camera extrinsics orientation, e.g. 1.0e-3 for online-calib [rad].
    sigma_c_relative_translation: 0.0 # The std. dev. of the cam. extr. transl. change between frames, e.g. 1.0e-6 for adaptive online calib (not less for numerics) [m].
    sigma_c_relative_orientation: 0.0 # The std. dev. of the cam. extr. orient. change between frames, e.g. 1.0e-6 for adaptive online calib (not less for numerics) [rad].
    # timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance




imu_params:
    a_max: 176.0 # acceleration saturation [m/s^2]
    g_max: 7.8 # gyro saturation [rad/s]

    # Gyroscope
    sigma_g_c: 0.0025411490629492976 # gyro noise density [rad/s/sqrt(Hz)] 
    
    sigma_bg: 8.55368076515601e-07 # gyro bias prior [rad/s]
    
    # Accelerometer [m/s^2/sqrt(Hz)]
    # sigma_a_c: 0.008330529915907017 # original
    sigma_a_c: 0.08330529915907017 # 10 times 

    # accelerometer bias prior [m/s^2]
    # sigma_ba: 2.34304645114941e-05  # original
    sigma_ba: 0.00011715232 # 5 times
    
    sigma_gw_c: 0.0000165 # gyro drift noise density [rad/s^s/sqrt(Hz)] 0.00000165
    sigma_aw_c: 0.0002874 # accelerometer drift noise density [m/s^2/sqrt(Hz)] 0.00002874
    tau: 3600.0 # reversion time constant, currently not in use [s]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    a0: [ 0.0, 0.0, 0.0 ] # Accelerometer bias [m/s^2]
    imu_rate: 100
    # tranform Body-Sensor (IMU)
    T_BS:
        [0.0000, 0.0000, 1.0000, -0.018,
         1.0000, 0.0000, 0.0000, -0.016,
         0.0000, 1.0000, 0.0000, 0.0,
         0.0000, 0.0000, 0.0000, 1.0000]

sonar_params:
    T_SSo:
        [0.0000, 1.0000, 0.0000, 0.015995,
         -1.0000, 0.0000, 0.0000, 0.125,
         0.0000, 0.0000, 1.0000, 0.128,
         0.0000, 0.0000, 0.0000, 1.0000] # Stereo Rig V2

# Estimator parameters
numKeyframes: 5 # number of keyframes in optimisation window
numImuFrames: 3 # number of frames linked by most recent nonlinear IMU error terms

# ceres optimization options
ceres_options:
    minIterations: 3   # minimum number of iterations always performed
    maxIterations: 10  # never do more than these, even if not converged
    timeLimit: 0.035   # [s] negative values will set the an unlimited time limit

# detection
detection_options:
    threshold: 20.0      # detection threshold. By default the uniformity radius in pixels
    octaves: 1           # number of octaves for detection. 0 means single-scale at highest resolution
    maxNoKeypoints: 100  # restrict to a maximum of this many keypoints per image (strongest ones)   #Sharmin

# delay of images [s]:
imageDelay: 0.0  # in case you are using a custom setup, you will have to calibrate this. 0 for the VISensor.

# display debug images?
displayImages: true  # displays debug video and keyframe matches. May be slow.
publishDebugImages: false  # publish debug image to topic ~debug_image_x

# use direct driver
useDriver: false

# some options for how and what to publish -- optional in ROS-free version
publishing_options:
    publish_rate: 100                  # rate at which odometry updates are published only works properly if imu_rate/publish_rate is an integer!!
    publishLandmarks: true             # select, if you want to publish landmarks at all
    landmarkQualityThreshold: 1.0e-2   # landmark with lower quality will not be published
    maximumLandmarkQuality: 0.05       # landmark with higher quality will be published with the maximum colour intensity
    maxPathLength: 20                  # maximum length of the published path
    publishImuPropagatedState: false    # Should the state that is propagated with IMU messages be published? Or just the optimized ones?
    # provide custom World frame Wc
    T_Wc_W:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
    trackedBodyFrame: B                # B or S, the frame of reference that will be expressed relative to the selected worldFrame
    velocitiesFrame: Wc                # Wc, B or S,  the frames in which the velocities of the selected trackedBodyFrame will be expressed in

#Sharmin
isSonarUsed: false
isDepthUsed: false
isRelocalization: true
histogramMethod: "CLAHE" # NONE, HISTOGRAM, CLAHE
claheClipLimit: 5.0 # 5.0
claheTilesGridSize: 8 # 8
resizeFactor: 1.0  # by default 1.0. set this value if you want to resize the original image by this factor. You DO NOT need to change camera/projection matrix, those will be updated accordingly. 
