%YAML:1.0
cameras:
    - {T_SC:
       [-0.9997049440882879, -0.021427083457493494, -0.011441366174378804, 0.010706013086579308,
        0.009978844795124786, 0.06716088802542239, -0.9976922560470183, -0.022204948460161276,
        0.02214604754770977, -0.9975120526661019, -0.06692725426814031, 0.45296798490113654,
          0.0, 0.0, 0.0, 1.0],
       image_dimension: [1920, 1080],
       distortion_coefficients: [-0.07154614806316285, 0.17275073737940927, -0.0009540854697760907, -0.008725871476365036],
       distortion_type: radialtangential,
       focal_length: [1282.6977865195622, 1282.0563933415326], #projection matrix as pre-rectified images have been used
       principal_point: [928.3250199345833, 517.4275148460564]} #projection matrix as pre-rectified images have been used

camera_params:
    camera_rate: 30
    sigma_absolute_translation: 0.0
    sigma_absolute_orientation: 0.0
    sigma_c_relative_translation: 0.0 # below 1.0e-6 ruines numerics...
    sigma_c_relative_orientation: 0.0 # below 1.0e-6 ruines numerics...


imu_params:
    a_max: 176.0 # acceleration saturation [m/s^2]
    g_max: 7.8 # gyro saturation [rad/s]

    # gyro noise density [rad/s/sqrt(Hz)]
    sigma_g_c: 0.0014831706669334573 # original
    # sigma_g_c: 0.014831706669334573 # 10 times

    # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_gw_c: 2.844609225511482e-05 # original

    sigma_bg: 0.03 # gyro bias prior [rad/s]


    # accelerometer noise density [m/s^2/sqrt(Hz)]
    # sigma_a_c: 0.001185848786246905 # original
    # sigma_a_c: 0.00741585333  # 5 times
    sigma_a_c: 0.01185848786246905 # 10 times

    # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    sigma_aw_c: 0.00021617527884731507 # original

    sigma_ba: 0.1 # accelerometer bias prior [m/s^2]  

    tau: 3600.0 # reversion time constant, currently not in use [s]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    a0: [ 0.0, 0.0, 0.0 ] # Accelerometer bias [m/s^2]
    imu_rate: 200
    # tranform Body-Sensor (IMU)
    T_BS:
        [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]
sonar_params:
    T_SSo:
        [0.0000, 1.0000, 0.0000, 0.015995,
         -1.0000, 0.0000, 0.0000, 0.125,
         0.0000, 0.0000, 1.0000, 0.128,
         0.0000, 0.0000, 0.0000, 1.0000] # Stereo Rig V2

#gyroscope_noise_density: 0.2e-3, gyroscope_random_walk: 2.8577e-006

# Estimator parameters
numKeyframes: 5 # number of keyframes in optimisation window
numImuFrames: 3 # number of frames linked by most recent nonlinear IMU error terms

# ceres optimization options
ceres_options:
    minIterations: 3   # minimum number of iterations always performed
    maxIterations: 10  # never do more than these, even if not converged
    timeLimit: -1   # [s] negative values will set the an unlimited time limit

# detection
detection_options:
    threshold: 40.0      # detection threshold. By default the uniformity radius in pixels
    octaves: 1 # 0          # number of octaves for detection. 0 means single-scale at highest resolution
    maxNoKeypoints: 400  # restrict to a maximum of this many keypoints per image (strongest ones)   #Sharmin

# delay of images [s]:
imageDelay: 0.0026822  # timeoffset

# display debug images?
displayImages: true  # displays debug video and keyframe matches. May be slow.

# use direct driver
useDriver: false

# some options for how and what to publish -- optional in ROS-free version
publishing_options:
    publish_rate: 30                 # rate at which odometry updates are published only works properly if imu_rate/publish_rate is an integer!!
    publishLandmarks: true             # select, if you want to publish landmarks at all
    landmarkQualityThreshold: 1.0e-2   # landmark with lower quality will not be published
    maximumLandmarkQuality: 0.05       # landmark with higher quality will be published with the maximum colour intensity
    maxPathLength: 100                  # maximum length of the published path
    publishImuPropagatedState: false    # Should the state that is propagated with IMU messages be published? Or just the optimized ones?
    # provide custom World frame Wc
    T_Wc_W:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
    trackedBodyFrame: B                # B or S, the frame of reference that will be expressed relative to the selected worldFrame
    velocitiesFrame: Wc                # Wc, B or S,  the frames in which the velocities of the selected trackedBodyFrame will be expressed in

#Sharmin
isSonarUsed: false
isDepthUsed: false
isRelocalization: false
histogramMethod: "CLAHE" # NONE, HISTOGRAM, CLAHE
claheClipLimit: 6.0 # 6.0
claheTilesGridSize: 4 # 8
resizeFactor: 0.5  # by default 1.0. set this value if you want to resize the original image by this factor. You DO NOT need to change camera/projection matrix, those will be updated accordingly. 